apiVersion: v1
kind: ServiceAccount
metadata:
  name: selfheal-manager
  namespace: netprobe-system
  labels:
    app.kubernetes.io/name: selfheal-network-operator
    app.kubernetes.io/component: manager
